<?php
session_start();
include_once 'Model/DataBase.php';
include_once 'Model/FunctionSummary.php';
include_once 'Model/League.php';
include_once 'Model/Asa.php';
include_once 'Model/Functions.php';
include_once 'Model/Members.php';
include_once 'Model/SportsEventsModel.php';
include_once 'Model/Competiton.php';
include_once 'Model/TypeOfCompetition.php';
include_once 'Model/Rally.php';
include_once 'Model/CategoryCompetition.php';
include_once 'Model/registrationforofficial.php';
include_once 'Model/RegistrationForCompetitors.php';
include_once 'Model/RaceOutsideRally.php';
$Function=array( 155);
$Responsible=array(155);
$Officiel=array( 155);
$Admin=array(155);